/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WButton {
    'color': 'plain' | 'primary' | 'secondary' | 'danger';
    'type': 'basic' | 'raised' | 'outline' | 'flat';
  }
  interface WSimpleCard {
    'description': string;
    'image': string;
    'title': string;
    'width': string;
  }
  interface WSwitch {
    'isCheked': boolean;
  }
}

declare global {


  interface HTMLWButtonElement extends Components.WButton, HTMLStencilElement {}
  var HTMLWButtonElement: {
    prototype: HTMLWButtonElement;
    new (): HTMLWButtonElement;
  };

  interface HTMLWSimpleCardElement extends Components.WSimpleCard, HTMLStencilElement {}
  var HTMLWSimpleCardElement: {
    prototype: HTMLWSimpleCardElement;
    new (): HTMLWSimpleCardElement;
  };

  interface HTMLWSwitchElement extends Components.WSwitch, HTMLStencilElement {}
  var HTMLWSwitchElement: {
    prototype: HTMLWSwitchElement;
    new (): HTMLWSwitchElement;
  };
  interface HTMLElementTagNameMap {
    'w-button': HTMLWButtonElement;
    'w-simple-card': HTMLWSimpleCardElement;
    'w-switch': HTMLWSwitchElement;
  }
}

declare namespace LocalJSX {
  interface WButton {
    'color'?: 'plain' | 'primary' | 'secondary' | 'danger';
    'type'?: 'basic' | 'raised' | 'outline' | 'flat';
  }
  interface WSimpleCard {
    'description'?: string;
    'image'?: string;
    'title'?: string;
    'width'?: string;
  }
  interface WSwitch {
    'isCheked'?: boolean;
  }

  interface IntrinsicElements {
    'w-button': WButton;
    'w-simple-card': WSimpleCard;
    'w-switch': WSwitch;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'w-button': LocalJSX.WButton & JSXBase.HTMLAttributes<HTMLWButtonElement>;
      'w-simple-card': LocalJSX.WSimpleCard & JSXBase.HTMLAttributes<HTMLWSimpleCardElement>;
      'w-switch': LocalJSX.WSwitch & JSXBase.HTMLAttributes<HTMLWSwitchElement>;
    }
  }
}


